In [ ]:
import numpy as np 
import pandas as pd
data=pd.read_json("AMAZON_FASHION_5.json",lines=True)

In [ ]:
data['reviewText'].str.lower()

In [ ]:
import re

def remove_html(text):
    if isinstance(text, str):
        pattern = re.compile('<.*?>')
        return pattern.sub('', text)
    else:
        return text

data['reviewText'] = data['reviewText'].apply(remove_html)

In [ ]:
data['reviewText']

In [ ]:
def remove_url(text):
    pattern =re.compile(r'http?://\S+|www\.\S+')
    return pattern.sub(r'',text)

In [ ]:
import string ,time
string.punctuation

In [ ]:
exclude=string.punctuation

In [ ]:
import string

exclude = string.punctuation

data['reviewText'] = data['reviewText'].fillna("")

data['reviewText'] = data['reviewText'].apply(
    lambda x: x.translate(str.maketrans('', '', exclude))
)

In [ ]:
def chat_con(text):
    next_text=[]
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [ ]:
#using TEXTBLOB FOR SPELLING CHECK 
!pip install -U textblob
data

In [ ]:
data

In [ ]:
from textblob import TextBlob
def spell(text):
    chat=[]
    for word in text.split():
        textb=TextBlob(word)
        chat.append(textb.correct().string)
    return " ".join(chat)

In [ ]:
#remove stop words
!pip install nltk
import nltk

In [ ]:
nltk.download('stopwords')
nltk.download('punkt')
from nltk.corpus import stopwords
stopwords.words('english')

In [ ]:
def remove_stopwords(text):   # stop words are the words which do not have naymeanin to the sentence , 
    new_text=[]
    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x=new_text[:]
    new_text.clear()
    return " ".join(x)

In [ ]:
data['reviewText'].apply(remove_stopwords)

In [ ]:
texts = data['reviewText'].astype(str).tolist()

#using regular expression creating tokenization

In [ ]:
data

In [ ]:
texts = data['reviewText'].astype(str).tolist()

tokens = []
for doc in nlp.pipe(texts, batch_size=50):
    tokens.append([token.text for token in doc])

data['tokens'] = tokens

In [56]:
data

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,vote,image
0,5,True,"09 4, 2015",ALJ66O1Y6SLHA,B000K2PJ4K,"{'Size:': ' Big Boys', 'Color:': ' Blue/Orange'}",Tonya B.,Great product and price,Five Stars,1441324800,NaN,NaN
1,5,True,"09 4, 2015",ALJ66O1Y6SLHA,B000K2PJ4K,"{'Size:': ' Big Boys', 'Color:': ' Black (3746...",Tonya B.,Great product and price,Five Stars,1441324800,NaN,NaN
2,5,True,"09 4, 2015",ALJ66O1Y6SLHA,B000K2PJ4K,"{'Size:': ' Big Boys', 'Color:': ' Blue/Gray L...",Tonya B.,Great product and price,Five Stars,1441324800,NaN,NaN
3,5,True,"09 4, 2015",ALJ66O1Y6SLHA,B000K2PJ4K,"{'Size:': ' Big Boys', 'Color:': ' Blue (37867...",Tonya B.,Great product and price,Five Stars,1441324800,NaN,NaN
4,5,True,"09 4, 2015",ALJ66O1Y6SLHA,B000K2PJ4K,"{'Size:': ' Big Boys', 'Color:': ' Blue/Pink'}",Tonya B.,Great product and price,Five Stars,1441324800,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3171,5,True,"07 2, 2018",A2077NII5H62R2,B005AGO4LU,"{'Size:': ' 8.5 B(M) US', 'Color:': ' Green Gl...",Amazon Customer,Perfect fit,Five Stars,1530489600,NaN,NaN
3172,5,True,"06 28, 2018",A2IBS6PIPAGAB5,B005AGO4LU,"{'Size:': ' 5 B(M) US', 'Color:': ' Wolf Grey/...",J. Avila,My favorite cross trainers,Comfortable,1530144000,NaN,NaN
3173,5,True,"06 25, 2018",A1GTC5EVSJNCQ8,B005AGO4LU,"{'Size:': ' 8 B(M) US', 'Color:': ' Blue Tint/...",Amazon Customer,Love them fit perfect,Five Stars,1529884800,NaN,NaN
3174,5,True,"06 20, 2018",A311XHHLM12MUT,B005AGO4LU,"{'Size:': ' 9 B(M) US', 'Color:': ' Blue Tint/...",Peter,Favorite Nike shoe ever The flex sole is excel...,Love them!,1529452800,NaN,NaN
3175,5,True,"06 16, 2018",A135SGOQMVWABQ,B005AGO4LU,"{'Size:': ' 9 B(M) US', 'Color:': ' Black/Whit...",Susan,I wear these everyday to work the gym etc,Five Stars,1529107200,NaN,NaN

In [57]:
texts = data['reviewText'].astype(str).tolist()

In [69]:
data

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,vote,image,lemmas
0,5,True,"09 4, 2015",ALJ66O1Y6SLHA,B000K2PJ4K,"{'Size:': ' Big Boys', 'Color:': ' Blue/Orange'}",Tonya B.,Great product and price,Five Stars,1441324800,NaN,NaN,"[great, product, and, price]"
1,5,True,"09 4, 2015",ALJ66O1Y6SLHA,B000K2PJ4K,"{'Size:': ' Big Boys', 'Color:': ' Black (3746...",Tonya B.,Great product and price,Five Stars,1441324800,NaN,NaN,"[great, product, and, price]"
2,5,True,"09 4, 2015",ALJ66O1Y6SLHA,B000K2PJ4K,"{'Size:': ' Big Boys', 'Color:': ' Blue/Gray L...",Tonya B.,Great product and price,Five Stars,1441324800,NaN,NaN,"[great, product, and, price]"
3,5,True,"09 4, 2015",ALJ66O1Y6SLHA,B000K2PJ4K,"{'Size:': ' Big Boys', 'Color:': ' Blue (37867...",Tonya B.,Great product and price,Five Stars,1441324800,NaN,NaN,"[great, product, and, price]"
4,5,True,"09 4, 2015",ALJ66O1Y6SLHA,B000K2PJ4K,"{'Size:': ' Big Boys', 'Color:': ' Blue/Pink'}",Tonya B.,Great product and price,Five Stars,1441324800,NaN,NaN,"[great, product, and, price]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3171,5,True,"07 2, 2018",A2077NII5H62R2,B005AGO4LU,"{'Size:': ' 8.5 B(M) US', 'Color:': ' Green Gl...",Amazon Customer,Perfect fit,Five Stars,1530489600,NaN,NaN,"[perfect, fit]"
3172,5,True,"06 28, 2018",A2IBS6PIPAGAB5,B005AGO4LU,"{'Size:': ' 5 B(M) US', 'Color:': ' Wolf Grey/...",J. Avila,My favorite cross trainers,Comfortable,1530144000,NaN,NaN,"[my, favorite, cross, trainer]"
3173,5,True,"06 25, 2018",A1GTC5EVSJNCQ8,B005AGO4LU,"{'Size:': ' 8 B(M) US', 'Color:': ' Blue Tint/...",Amazon Customer,Love them fit perfect,Five Stars,1529884800,NaN,NaN,"[love, they, fit, perfect]"
3174,5,True,"06 20, 2018",A311XHHLM12MUT,B005AGO4LU,"{'Size:': ' 9 B(M) US', 'Color:': ' Blue Tint/...",Peter,Favorite Nike shoe ever The flex sole is excel...,Love them!,1529452800,NaN,NaN,"[favorite, Nike, shoe, ever, the, flex, sole, ..."
3175,5,True,"06 16, 2018",A135SGOQMVWABQ,B005AGO4LU,"{'Size:': ' 9 B(M) US', 'Color:': ' Black/Whit...",Susan,I wear these everyday to work the gym etc,Five Stars,1529107200,NaN,NaN,"[I, wear, these, everyday, to, work, the, gym,..."

In [61]:
import spacy
nlp = spacy.load("en_core_web_sm")

lemmas = []
for doc in nlp.pipe(texts, batch_size=50):
    lemmas.append([token.lemma_ for token in doc if token.is_alpha])

data['lemmas'] = lemmas

In [64]:
final_data=data['lemmas']

In [66]:
texts = [" ".join(words) for words in final_data]

In [70]:
texts = data['lemmas'].apply(lambda x: " ".join(x))

In [71]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)

X = vectorizer.fit_transform(texts)

In [72]:
y = data['overall']

In [73]:
y = data['overall'].apply(lambda x: 1 if x >= 3 else 0)

In [74]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LogisticRegression()
model.fit(X_train, y_train)

print(model.score(X_test, y_test))

0.9638364779874213

In [75]:
print(y.value_counts())

overall
1    2966
0     210
Name: count, dtype: int64

In [76]:
from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))

[[ 18  23]
 [  0 595]]

In [77]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.44      0.61        41
           1       0.96      1.00      0.98       595

    accuracy                           0.96       636
   macro avg       0.98      0.72      0.80       636
weighted avg       0.97      0.96      0.96       636

In [78]:
import joblib

# Save model
joblib.dump(model, "sentiment_model.pkl")

# Save vectorizer
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

['tfidf_vectorizer.pkl']